### PR TITLE
Ensure correct request URL

### PR DESCRIPTION
**Pull request by mattheu**
I was running into an error when I tried to run this plugin locally - the AJAX request was 404ing.

Problem was `get_permalink` was returning a string without a trailing slash. The JS used to build the request URL is expecting it have one.

I thought it was neater to unslash the permalink passed to the JS, and then join the URL bits with a slash.

This should be a bit more robust.

### CODE REVIEW

**Comment by goldenapples** [comment]
Looks good. I don't know that I've ever worked with a permalink structure that didn't have a trailing slash, so I didn't even think of it. 

Now that I look back over it, I can't remember why I didn't just use the already available `liveblog_settings.endpoint_url` value, which also contains logic to handle permalinks like `?p=1&liveblog=`.

**Comment by mattheu** [comment]
Good call on `liveblog_settings.endpoint_url` I don't know the plugin very well.

I've updated the pull request.

**Comment by goldenapples** [comment]
Hmm. I'm trying to test this out and remembering why I didn't use the `liveblog_settings.endpoint_url` value: VIP does some weird rewrites on that value (changing it to something like `__liveblog_{postID}`, which this plugin couldn't handle. Can you revert back to the first commit, and I'll merge this?

**Comment by mattheu** [comment]
Reverted. Thanks for looking at this!

**Pull request merged**
